app_name="golang daily lib -- viper"

log_level="DEBUG"

[mysql]
ip="127.0.0.1"
port = 3306
user = "root"
password = 123456
database = "awesome"

[redis]
ip = "127.0.0.1"
port = 6381

[server]
protocols = ["https","http","ftp"]
ports = [10000,10001,10002]
timeout = "3s"